# argocd application.yaml for app1
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
spec:
  project: default
  source:
    repoURL: git@github.com:renatoruis/gitops.git
    targetRevision: HEAD
    path: app1
  destination:
    server: https://kubernetes.default.svc
    namespace: default