# deployment.yaml for apache httpd
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-httpd
  labels:
    app: apache-httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-httpd
  template:
    metadata:
      labels:
        app: apache-httpd
    spec:
      containers:
        - name: apache-httpd
          image: httpd:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m